$dbd_oracle_mm_opts = {
                        'DIR' => [],
                        'PREREQ_PM' => {
                                         'DBI' => '1.51'
                                       },
                        'dynamic_lib' => {
                                           'OTHERLDFLAGS' => ''
                                         },
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*'
                                   },
                        'OBJECT' => '$(O_FILES)',
                        'NAME' => 'DBD::Oracle',
                        'LIBS' => [
                                    '-L/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64 -lclntsh'
                                  ],
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                        'dist' => {
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist',
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir',
                                    'SUFFIX' => 'gz',
                                    'COMPRESS' => 'gzip -v9'
                                  },
                        'INC' => '-I/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64/sdk/include -I/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/DBI',
                        'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                        'LICENSE' => 'perl',
                        'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                        'META_MERGE' => {
                                          'configure_requires' => {
                                                                    'DBI' => '1.51'
                                                                  },
                                          'resources' => {
                                                           'repository' => {
                                                                             'url' => 'git://github.com/yanick/DBD-Oracle.git',
                                                                             'type' => 'git',
                                                                             'web' => 'http://github.com/yanick/DBD-Oracle/tree'
                                                                           },
                                                           'bugtracker' => {
                                                                             'web' => 'http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle',
                                                                             'mailto' => 'bug-dbd-oracle at rt.cpan.org'
                                                                           },
                                                           'homepage' => 'http://search.cpan.org/dist/DBD-Oracle'
                                                         },
                                          'build_requires' => {
                                                                'DBI' => '1.51',
                                                                'Test::Simple' => '0.90',
                                                                'ExtUtils::MakeMaker' => 0
                                                              }
                                        }
                      };
$dbd_oracle_mm_self = bless( {
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'RM_F' => 'rm -f',
                               'CI' => 'ci -u',
                               'DIST_DEFAULT' => 'tardist',
                               'DESTINSTALLSITESCRIPT' => '$(DESTDIR)$(INSTALLSITESCRIPT)',
                               'BUILD_REQUIRES' => {},
                               'PM' => {
                                         'lib/DBD/Oracle/Troubleshooting/Macos.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Macos.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Aix.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Aix.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Sun.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Sun.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Linux.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Linux.pod',
                                         'lib/DBD/Oracle/Troubleshooting.pod' => 'blib/lib/DBD/Oracle/Troubleshooting.pod',
                                         'lib/DBD/Oracle.pm' => 'blib/lib/DBD/Oracle.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Hpux.pod',
                                         'lib/DBD/Oracle/Object.pm' => 'blib/lib/DBD/Oracle/Object.pm',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib/lib/DBD/Oracle/GetInfo.pm',
                                         'mk.pm' => '$(INST_LIB)/DBD/mk.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Cygwin.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Win64.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Win64.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Win32.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Win32.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Vms.pod' => 'blib/lib/DBD/Oracle/Troubleshooting/Vms.pod'
                                       },
                               'DIST_CP' => 'best',
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'exe_ext',
                                             'full_ar',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'BSLOADLIBS' => '',
                               'SHELL' => '/bin/sh',
                               'EXE_EXT' => '',
                               'VENDORLIBEXP' => '',
                               'TAR' => 'tar',
                               'INSTALLARCHLIB' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi',
                               'BASEEXT' => 'Oracle',
                               'COMPRESS' => 'gzip --best',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)/$(BASEEXT)$(LIB_EXT)',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'PL_FILES' => {},
                               'PERM_DIR' => 755,
                               'MAN1EXT' => '1',
                               'INST_MAN3DIR' => 'blib/man3',
                               'VERSION_MACRO' => 'VERSION',
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'FIXIN' => '$(ABSPERLRUN) -MExtUtils::MY -e \'MY->fixin(shift)\' --',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'SITEARCHEXP' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi',
                               'TEST_S' => 'test -s',
                               'OSNAME' => 'linux',
                               'MACROSTART' => '',
                               'INSTALLVENDORSCRIPT' => '',
                               'PARENT_NAME' => 'DBD',
                               'VENDORPREFIX' => '',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'PERL_INCDEP' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi/CORE',
                               'PERL_CORE' => 0,
                               'INC' => '-I/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64/sdk/include -I/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/DBI',
                               'OSVERS' => '4.14.88-88.76.amzn2.x86_64',
                               'MKPATH' => '$(ABSPERLRUN) -MExtUtils::Command -e \'mkpath\' --',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'INSTALLSITEMAN1DIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/man/man1',
                               'TEST_F' => 'test -f',
                               'SO' => 'so',
                               'ECHO_N' => 'echo -n',
                               'VENDORARCHEXP' => '',
                               'MAKEFILE' => 'Makefile',
                               'INSTALLMAN1DIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/man/man1',
                               'INSTALLSITEMAN3DIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/man/man3',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'INST_MAN1DIR' => 'blib/man1',
                               'MM_Unix_VERSION' => '7.3',
                               'MAKEMAKER' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/ExtUtils/MakeMaker.pm',
                               'PMLIBPARENTDIRS' => [
                                                      'lib'
                                                    ],
                               'NAME_SYM' => 'DBD_Oracle',
                               'UNINST' => 0,
                               'LINKTYPE' => 'dynamic',
                               'USEMAKEFILE' => '-f',
                               'LDFROM' => '$(OBJECT)',
                               'SHAR' => 'shar',
                               'PREREQ_PM' => {
                                                'DBI' => '1.51'
                                              },
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'HAS_LINK_CODE' => 1,
                               'SKIPHASH' => {},
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'SUFFIX' => '.gz',
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'RM_RF' => 'rm -rf',
                               'PERL_ARCHIVE' => '',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'warn_if_old_packlist\' --',
                               'INSTALLDIRS' => 'site',
                               'INST_BIN' => 'blib/bin',
                               'INSTALLVENDORARCH' => '',
                               'PERL_ARCHLIBDEP' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)/auto/$(FULLEXT)',
                               'INSTALLSITEARCH' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi',
                               'VERSION' => '1.74',
                               'DEV_NULL' => '> /dev/null 2>&1',
                               'TEST_REQUIRES' => {},
                               'INSTALLVENDORMAN1DIR' => '',
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'INSTALLSCRIPT' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin',
                               'CONFIGURE_REQUIRES' => {},
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.3 (Revision: 73000) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
',
                                             '#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     AUTHOR => [q[Tim Bunce (dbi-users@perl.org)]]',
                                             '#     BUILD_REQUIRES => {  }',
                                             '#     CONFIGURE_REQUIRES => {  }',
                                             '#     DEFINE => q[ -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112]',
                                             '#     DIR => []',
                                             '#     INC => q[-I/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64/sdk/include -I/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/DBI]',
                                             '#     LIBS => [q[-L/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64 -lclntsh]]',
                                             '#     LICENSE => q[perl]',
                                             '#     META_MERGE => { build_requires=>{ DBI=>q[1.51], ExtUtils::MakeMaker=>q[0], Test::Simple=>q[0.90] }, configure_requires=>{ DBI=>q[1.51] }, resources=>{ bugtracker=>{ mailto=>q[bug-dbd-oracle at rt.cpan.org], web=>q[http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle] }, homepage=>q[http://search.cpan.org/dist/DBD-Oracle], repository=>{ type=>q[git], url=>q[git://github.com/yanick/DBD-Oracle.git], web=>q[http://github.com/yanick/DBD-Oracle/tree] } } }',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[1.51] }',
                                             '#     TEST_REQUIRES => {  }',
                                             '#     VERSION_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { COMPRESS=>q[gzip -v9], DIST_DEFAULT=>q[clean distcheck disttest tardist], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '#     dynamic_lib => { OTHERLDFLAGS=>q[] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'ZIPFLAGS' => '-r',
                               'LIB_EXT' => '.a',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)/DBD',
                               'PERM_RWX' => 755,
                               'DESTINSTALLVENDORHTMLDIR' => '$(DESTDIR)$(INSTALLVENDORHTMLDIR)',
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'EXPORT_LIST' => '',
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'CP' => 'cp',
                               'SITELIBEXP' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1',
                               'PERL_MALLOC_DEF' => '-DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc',
                               'SITEPREFIX' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------',
                               'INST_AUTODIR' => '$(INST_LIB)/auto/$(FULLEXT)',
                               'MAN3EXT' => '3',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'INSTALLVENDORBIN' => '',
                               'DESTINSTALLVENDORSCRIPT' => '$(DESTDIR)$(INSTALLVENDORSCRIPT)',
                               'EXTRALIBS' => '-L/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64 -lclntsh',
                               'INSTALLMAN3DIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/man/man3',
                               'BOOTDEP' => '',
                               'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                               'ABSTRACT' => 'Oracle database driver for the DBI module',
                               'INSTALLVENDORMAN3DIR' => '',
                               'INSTALLSITEBIN' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin',
                               'OBJ_EXT' => '.o',
                               'VERSION_SYM' => '1_74',
                               'OBJECT' => '$(O_FILES)',
                               'INST_LIB' => 'blib/lib',
                               'MAKE' => 'make',
                               'ECHO' => 'echo',
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'CP_NONEMPTY' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'cp_nonempty\' --',
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                               'MV' => 'mv',
                               'UNINSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'uninstall\' --',
                               'CHMOD' => 'chmod',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'AR_STATIC_ARGS' => 'cr',
                               'MM_VERSION' => '7.3',
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)',
                               'INST_HTMLDIR' => 'blib/html',
                               'INST_SCRIPT' => 'blib/script',
                               'O_FILES' => [
                                              'Oracle.o',
                                              'dbdimp.o',
                                              'oci8.o'
                                            ],
                               'INST_LIBDIR' => '$(INST_LIB)/DBD',
                               'PERL_INC' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi/CORE',
                               'TARFLAGS' => 'cvf',
                               'DIRFILESEP' => '/',
                               'MAN3PODS' => {
                                               'lib/DBD/Oracle/Troubleshooting/Win64.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Win64.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Win32.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Win32.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Vms.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Vms.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Object.pm' => '$(INST_MAN3DIR)/DBD::Oracle::Object.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Hpux.$(MAN3EXT)',
                                               'lib/DBD/Oracle.pm' => '$(INST_MAN3DIR)/DBD::Oracle.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Cygwin.$(MAN3EXT)',
                                               'lib/DBD/Oracle/GetInfo.pm' => '$(INST_MAN3DIR)/DBD::Oracle::GetInfo.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Aix.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Aix.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Macos.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Macos.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Linux.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Linux.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Sun.pod' => '$(INST_MAN3DIR)/DBD::Oracle::Troubleshooting::Sun.$(MAN3EXT)'
                                             },
                               'INSTALLSITEHTMLDIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/html',
                               'PERL_ARCHIVE_AFTER' => '',
                               'ARGS' => {
                                           'AUTHOR' => [
                                                         'Tim Bunce (dbi-users@perl.org)'
                                                       ],
                                           'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                                           'INC' => '-I/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64/sdk/include -I/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi/auto/DBI',
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                                           'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                                           'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                                           'LICENSE' => 'perl',
                                           'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'OBJECT' => '$(O_FILES)',
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'NAME' => 'DBD::Oracle'
                                         },
                               'LD' => 'gcc',
                               'MACROEND' => '',
                               'NAME' => 'DBD::Oracle',
                               'INSTALLBIN' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin',
                               'LD_RUN_PATH' => '/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64',
                               'AUTHOR' => $dbd_oracle_mm_self->{'ARGS'}{'AUTHOR'},
                               'PERL_SRC' => undef,
                               'DESTINSTALLSITEHTMLDIR' => '$(DESTDIR)$(INSTALLSITEHTMLDIR)',
                               'INST_ARCHLIB' => 'blib/arch',
                               'INSTALLVENDORLIB' => '',
                               'DLBASE' => '$(BASEEXT)',
                               'NOECHO' => '@',
                               'LDLOADLIBS' => '-L/build/camel/work-padpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpadpad/oracle-instantclient-linux64 -lclntsh',
                               'TRUE' => 'true',
                               'LDFLAGS' => ' -fstack-protector-strong',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e \'install([ from_to => {@ARGV}, verbose => \'\\\'\'$(VERBINST)\'\\\'\', uninstall_shadows => \'\\\'\'$(UNINST)\'\\\'\', dir_mode => \'\\\'\'$(PERM_DIR)\'\\\'\' ]);\' --',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'DISTVNAME' => 'DBD-Oracle-1.74',
                               'DOC_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e \'perllocal_install\' --',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)/$(DLBASE).$(DLEXT)',
                               'LDDLFLAGS' => '-shared -O2 -fstack-protector-strong',
                               'PERLRUN' => '$(PERL)',
                               'DISTNAME' => 'DBD-Oracle',
                               'INSTALLHTMLDIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/html',
                               'TOUCH' => 'touch',
                               'LIBPERL_A' => 'libperl.a',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'NOOP' => '$(TRUE)',
                               'PERL_ARCHLIB' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi',
                               'PERL_ARCHIVEDEP' => '',
                               'UMASK_NULL' => 'umask 0',
                               'LIBC' => 'libc-2.12.so',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'INSTALLPRIVLIB' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1',
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'FULLEXT' => 'DBD/Oracle',
                               'LICENSE' => 'perl',
                               'AR' => 'ar',
                               'CCCDLFLAGS' => '-fPIC',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'PREFIX' => '$(SITEPREFIX)',
                               'FULL_AR' => '/opt/rh/devtoolset-3/root/usr/bin/ar',
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'DLSRC' => 'dl_dlopen.xs',
                               'INSTALLSITESCRIPT' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin',
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) -MExtUtils::Command -e \'eqtime\' --',
                               'VERBINST' => 0,
                               'PERLPREFIX' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------',
                               'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                               'DLEXT' => 'so',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'INSTALLVENDORHTMLDIR' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/html',
                               'RANLIB' => ':',
                               'DESTDIR' => '',
                               'CC' => 'gcc',
                               'MM_REVISION' => 73000,
                               'PERL_LIB' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1',
                               'DEFINE' => ' -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"12.2.0.1\\" -DORA_OCI_102 -DORA_OCI_112',
                               'XS_VERSION' => '1.74',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)/$(BASEEXT).bs',
                               'PERM_RW' => 644,
                               'PERLMAINCC' => '$(CC)',
                               'DESTINSTALLHTMLDIR' => '$(DESTDIR)$(INSTALLHTMLDIR)',
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'ABSPERL' => '$(PERL)',
                               'FALSE' => 'false',
                               'PERL' => '"/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin/perl-static"',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'ZIP' => 'zip',
                               'FULLPERL' => '"/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/bin/perl-static"',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'INSTALLSITELIB' => '/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/site_perl/5.28.1',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                               'CCDLFLAGS' => '-Wl,-E -Wl,-rpath,/tmp/ActiveState------------------------------------------please-run-the-install-script-----------------------------------------/lib/perl5/5.28.1/x86_64-linux-thread-multi/CORE',
                               'MAP_TARGET' => 'perl'
                             }, 'PACK001' );
